class_name BalanceReport
extends RefCounted
## Turns round-robin results into a markdown report.

const FLAG_LOW: float = 0.35
const FLAG_HIGH: float = 0.65
const TOP_CARDS: int = 8


static func build(decks: Array[Deck], results: Array[MatchupStats], games_per_matchup: int, notes: String = "") -> String:
	var lines: PackedStringArray = PackedStringArray()
	lines.append("# Balance Report")
	lines.append("")
	lines.append("Generated by `tools/run_simulation.gd`: AI vs AI (balanced personality), %d games per matchup," % games_per_matchup)
	lines.append("alternating who goes first, hand smoother on, one free mulligan. Draws count as half a win.")
	lines.append("Games not finished within the turn limit are draws.")
	lines.append("")
	lines.append_array(_standings(decks, results))
	lines.append_array(_matrix(decks, results))
	lines.append_array(_matchup_table(results))
	lines.append_array(_card_usage(decks, results))
	lines.append_array(_flags(results))
	if notes != "":
		lines.append("## Analysis")
		lines.append("")
		lines.append(notes)
		lines.append("")
	return "\n".join(lines)


static func _standings(decks: Array[Deck], results: Array[MatchupStats]) -> PackedStringArray:
	var lines: PackedStringArray = PackedStringArray()
	var rows: Array[Dictionary] = []
	for deck: Deck in decks:
		var games: int = 0
		var points: float = 0.0
		for stats: MatchupStats in results:
			if stats.deck_a == deck.deck_name:
				games += stats.games
				points += float(stats.wins_a) + 0.5 * float(stats.draws)
			elif stats.deck_b == deck.deck_name:
				games += stats.games
				points += float(stats.wins_b) + 0.5 * float(stats.draws)
		rows.append({"name": deck.deck_name, "games": games, "rate": points / float(maxi(1, games))})
	rows.sort_custom(func(a: Dictionary, b: Dictionary) -> bool: return float(a["rate"]) > float(b["rate"]))
	lines.append("## Standings")
	lines.append("")
	lines.append("| Deck | Games | Win rate |")
	lines.append("|------|------:|---------:|")
	for row: Dictionary in rows:
		lines.append("| %s | %d | %s |" % [row["name"], int(row["games"]), _pct(float(row["rate"]))])
	lines.append("")
	var total_games: int = 0
	var total_turns: int = 0
	for stats: MatchupStats in results:
		total_games += stats.games
		total_turns += stats.total_turns
	lines.append("Average game length: **%.1f turns** (both players' turns) over %d games." % [float(total_turns) / float(maxi(1, total_games)), total_games])
	lines.append("")
	return lines


static func _matrix(decks: Array[Deck], results: Array[MatchupStats]) -> PackedStringArray:
	var lines: PackedStringArray = PackedStringArray()
	lines.append("## Win-rate matrix (row deck vs column deck)")
	lines.append("")
	var header: String = "| |"
	var divider: String = "|---|"
	for deck: Deck in decks:
		header += " %s |" % deck.deck_name
		divider += "---:|"
	lines.append(header)
	lines.append(divider)
	for row_deck: Deck in decks:
		var row: String = "| **%s** |" % row_deck.deck_name
		for col_deck: Deck in decks:
			row += " %s |" % _cell(row_deck.deck_name, col_deck.deck_name, results)
		lines.append(row)
	lines.append("")
	return lines


static func _cell(row_name: String, col_name: String, results: Array[MatchupStats]) -> String:
	if row_name == col_name:
		return "-"
	for stats: MatchupStats in results:
		if stats.deck_a == row_name and stats.deck_b == col_name:
			return _pct(stats.win_rate_a())
		if stats.deck_a == col_name and stats.deck_b == row_name:
			return _pct(1.0 - stats.win_rate_a())
	return "-"


static func _matchup_table(results: Array[MatchupStats]) -> PackedStringArray:
	var lines: PackedStringArray = PackedStringArray()
	lines.append("## Matchups")
	lines.append("")
	lines.append("| Deck A | Deck B | Games | A wins | B wins | Draws | Avg turns | First player wins |")
	lines.append("|--------|--------|------:|-------:|-------:|------:|----------:|------------------:|")
	for stats: MatchupStats in results:
		lines.append("| %s | %s | %d | %d | %d | %d | %.1f | %s |" % [
			stats.deck_a, stats.deck_b, stats.games, stats.wins_a, stats.wins_b, stats.draws,
			stats.average_turns(), _pct(stats.first_player_win_rate()),
		])
	lines.append("")
	return lines


static func _card_usage(decks: Array[Deck], results: Array[MatchupStats]) -> PackedStringArray:
	var lines: PackedStringArray = PackedStringArray()
	lines.append("## Most-played cards")
	lines.append("")
	lines.append("Average casts per game (spells only; lands excluded), top %d per deck." % TOP_CARDS)
	lines.append("")
	for deck: Deck in decks:
		var totals: Dictionary = {}
		var games: int = 0
		for stats: MatchupStats in results:
			if stats.deck_a == deck.deck_name:
				games += stats.games
				MatchupStats._merge(totals, stats.casts_a)
			elif stats.deck_b == deck.deck_name:
				games += stats.games
				MatchupStats._merge(totals, stats.casts_b)
		var ranked: Array[String] = []
		for id: Variant in totals.keys():
			ranked.append(str(id))
		ranked.sort_custom(func(a: String, b: String) -> bool: return int(totals[a]) > int(totals[b]))
		var parts: PackedStringArray = PackedStringArray()
		for i: int in range(mini(TOP_CARDS, ranked.size())):
			parts.append("%s (%.2f)" % [ranked[i], float(totals[ranked[i]]) / float(maxi(1, games))])
		lines.append("- **%s**: %s" % [deck.deck_name, ", ".join(parts)])
		lines.append("  - least played: %s" % _least_played(deck, totals, games))
	lines.append("")
	return lines


static func _flags(results: Array[MatchupStats]) -> PackedStringArray:
	var lines: PackedStringArray = PackedStringArray()
	lines.append("## Flagged matchups")
	lines.append("")
	lines.append("Matchups outside %s-%s (either side):" % [_pct(FLAG_LOW), _pct(FLAG_HIGH)])
	lines.append("")
	var any: bool = false
	for stats: MatchupStats in results:
		var rate: float = stats.win_rate_a()
		if rate < FLAG_LOW or rate > FLAG_HIGH:
			any = true
			lines.append("- %s vs %s: %s / %s" % [stats.deck_a, stats.deck_b, _pct(rate), _pct(1.0 - rate)])
	if not any:
		lines.append("- none")
	lines.append("")
	var unfinished: int = 0
	for stats: MatchupStats in results:
		unfinished += stats.draws
	lines.append("Drawn / unfinished games: %d. Illegal AI actions: %d." % [unfinished, _illegal(results)])
	lines.append("")
	return lines


static func _illegal(results: Array[MatchupStats]) -> int:
	var total: int = 0
	for stats: MatchupStats in results:
		total += stats.illegal_actions
	return total


static func _pct(value: float) -> String:
	return "%.0f%%" % (value * 100.0)


## The deck's three spells cast least often per copy in the deck (cards that may be underpowered
## or that the AI does not know how to use).
static func _least_played(deck: Deck, totals: Dictionary, games: int) -> String:
	var copies: Dictionary = {}
	for card: CardData in deck.cards:
		if not card.is_land():
			copies[card.id] = int(copies.get(card.id, 0)) + 1
	var ids: Array[String] = []
	for id: Variant in copies.keys():
		ids.append(str(id))
	var rate: Callable = func(id: String) -> float:
		return float(totals.get(id, 0)) / float(maxi(1, games)) / float(copies[id])
	ids.sort_custom(func(a: String, b: String) -> bool: return float(rate.call(a)) < float(rate.call(b)))
	var parts: PackedStringArray = PackedStringArray()
	for i: int in range(mini(3, ids.size())):
		parts.append("%s (%.2f per copy)" % [ids[i], float(rate.call(ids[i]))])
	return ", ".join(parts)
