extends Node
## Sound effects and music. Sound names live in AudioCatalog; music tracks are generated by
## MusicSynth. Missing files are skipped silently so the game never crashes over audio.

const POOL_SIZE: int = 12

var _catalog: Dictionary = AudioCatalog.sounds()
var _cache: Dictionary = {}
var _pool: Array[AudioStreamPlayer] = []
var _music_a: AudioStreamPlayer
var _music_b: AudioStreamPlayer
var _music_active: AudioStreamPlayer
var _music_name: StringName = &""
var _rng: RandomNumberGenerator = RandomNumberGenerator.new()
var _last_played: Dictionary = {}
var _wanted_music: StringName = &""
var _music_fade: float = 1.2


func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	_rng.randomize()
	for i: int in range(POOL_SIZE):
		var player: AudioStreamPlayer = AudioStreamPlayer.new()
		player.bus = Settings.BUS_SFX
		add_child(player)
		_pool.append(player)
	if DisplayServer.get_name() != "headless":
		MusicSynth.warm_up()
	_music_a = _make_music_player()
	_music_b = _make_music_player()
	_music_active = _music_a


func _make_music_player() -> AudioStreamPlayer:
	var player: AudioStreamPlayer = AudioStreamPlayer.new()
	player.bus = Settings.BUS_MUSIC
	player.volume_db = -80.0
	add_child(player)
	return player


## Plays a named sound effect. `pitch_jitter` randomizes pitch a little to avoid repetition.
func sfx(sound: StringName, volume_db: float = 0.0, pitch_jitter: float = 0.05) -> void:
	if DisplayServer.get_name() == "headless":
		return
	var stream: AudioStream = _stream_for(sound)
	if stream == null:
		return
	# Drop identical sounds fired in the same few milliseconds (e.g. many hover events).
	var now: int = Time.get_ticks_msec()
	if now - int(_last_played.get(sound, -1000)) < 40:
		return
	_last_played[sound] = now
	for player: AudioStreamPlayer in _pool:
		if not player.playing:
			player.stream = stream
			player.volume_db = volume_db
			player.pitch_scale = 1.0 + _rng.randf_range(-pitch_jitter, pitch_jitter)
			player.play()
			return


func _stream_for(sound: StringName) -> AudioStream:
	var options: Array = _catalog.get(sound, [])
	if options.is_empty():
		return MusicSynth.sfx_stream(sound)
	var path: String = str(options[_rng.randi() % options.size()])
	if _cache.has(path):
		return _cache[path] as AudioStream
	var stream: AudioStream = null
	if ResourceLoader.exists(path):
		stream = load(path) as AudioStream
	_cache[path] = stream
	return stream


## Crossfades to a music track (see MusicSynth.TRACKS). Empty name stops the music. Tracks are
## rendered on a background thread at startup, so the request is retried until one is ready.
func play_music(track: StringName, fade: float = 1.2) -> void:
	_wanted_music = track
	_music_fade = fade
	_try_start_music()


func _exit_tree() -> void:
	MusicSynth.finish()


func _process(_delta: float) -> void:
	if _wanted_music != _music_name:
		_try_start_music()


func _try_start_music() -> void:
	if DisplayServer.get_name() == "headless":
		_music_name = _wanted_music
		return
	var track: StringName = _wanted_music
	if track == _music_name:
		return
	var previous: AudioStreamPlayer = _music_active
	if track == &"":
		_music_name = track
		_fade(previous, -80.0, _music_fade, true)
		return
	var stream: AudioStream = MusicSynth.track(track)
	if stream == null:
		return
	_music_name = track
	_music_active = _music_b if previous == _music_a else _music_a
	_music_active.stream = stream
	_music_active.volume_db = -80.0
	_music_active.play()
	_fade(_music_active, -6.0, _music_fade, false)
	_fade(previous, -80.0, _music_fade, true)


func _fade(player: AudioStreamPlayer, target_db: float, duration: float, stop_after: bool) -> void:
	var tween: Tween = create_tween()
	tween.tween_property(player, "volume_db", target_db, duration)
	if stop_after:
		tween.tween_callback(player.stop)
