class_name QuestCatalog
extends RefCounted
## Loads every quest from `data/quests/*.tres` (generated by tools/generate_quests.gd from
## `QuestDefinitions`; the .tres files are what the game reads, so they can be edited directly).

const DIR: String = "res://data/quests/"

static var _cache: Array[QuestData] = []


static func all() -> Array[QuestData]:
	if _cache.is_empty():
		var dir: DirAccess = DirAccess.open(DIR)
		if dir != null:
			var names: PackedStringArray = dir.get_files()
			names.sort()
			for file_name: String in names:
				var clean: String = file_name.trim_suffix(".remap")
				if clean.ends_with(".tres"):
					var quest: QuestData = load(DIR + clean) as QuestData
					if quest != null:
						_cache.append(quest)
	_cache.sort_custom(func(a: QuestData, b: QuestData) -> bool: return a.order < b.order)
	return _cache


static func find(quest_id: String) -> QuestData:
	for quest: QuestData in all():
		if quest.id == quest_id:
			return quest
	return null
