extends SceneTree
## The card importer. Reads data/source/card_list.csv + token_list.csv + data/scripts/*.txt and produces the card and token
## resources, plus docs/card_import_report.md. See docs/card_pipeline.md.
##
##   bash tools/import_cards.sh                  dry run: parse, validate, write only the report
##   bash tools/import_cards.sh --write          also write data/cards/<ID>.tres and data/tokens/<ID>.tres
##   bash tools/import_cards.sh --write --clean  ... and delete resources of cards that are no longer in the sheets
##   bash tools/import_cards.sh --stamp          record the sheet's current rules-text hash in every script header
##                                               (run it after re-scripting changed cards)

const REPORT_PATH: String = "res://docs/card_import_report.md"
const MANIFEST_PATH: String = "res://data/source/import_manifest.csv"


func _init() -> void:
	var args: PackedStringArray = OS.get_cmdline_user_args()
	var write: bool = args.has("--write")
	var clean: bool = args.has("--clean")
	var stamp: bool = args.has("--stamp")
	var entries: Array[CardImporter.Entry] = CardImporter.build_all()
	if stamp:
		_stamp_scripts(entries)
		entries = CardImporter.build_all()
	var previous: Dictionary = _read_manifest()
	var report: String = build_report(entries, previous)
	_write_text(REPORT_PATH, report)
	var problems: int = _problem_count(entries, previous)
	if write:
		var written: int = _write_resources(entries, clean)
		_write_manifest(entries)
		print("Wrote %d resources." % written)
	print("Imported %d cards and tokens; %d problems. Report: docs/card_import_report.md" % [entries.size(), problems])
	quit(0)


# ---- Report -------------------------------------------------------------------------------------------


static func build_report(entries: Array[CardImporter.Entry], previous: Dictionary) -> String:
	var new_ids: Array[String] = []
	var changed: Array[String] = []
	var unsupported: Array[String] = []
	var broken: Array[String] = []
	var present: Dictionary = {}
	var cards: int = 0
	var tokens: int = 0
	for entry: CardImporter.Entry in entries:
		present[entry.id] = true
		if entry.is_token:
			tokens += 1
		else:
			cards += 1
		if not entry.has_script and _scriptless_needs(entry):
			new_ids.append("%s %s (needs a script)" % [entry.id, entry.data.display_name])
		elif not previous.is_empty() and not previous.has(entry.id):
			new_ids.append("%s %s (new in the sheet)" % [entry.id, entry.data.display_name])
		if entry.has_script and not entry.script_hash.is_empty() and entry.script_hash != entry.text_hash:
			changed.append("%s %s: the rules text in the sheet changed since it was scripted. Now: \"%s\"" % [entry.id, entry.data.display_name, entry.rules_text.replace("\n", " / ")])
		if entry.has_script and entry.script_hash.is_empty():
			changed.append("%s %s: script has no recorded text hash (run --stamp once it has been checked)" % [entry.id, entry.data.display_name])
		for name: String in entry.unsupported:
			unsupported.append("%s %s: %s" % [entry.id, entry.data.display_name, name])
		for message: String in entry.problems:
			if message != "no script":
				broken.append("%s %s: %s" % [entry.id, entry.data.display_name, message])
	var removed: Array[String] = []
	for id: Variant in previous.keys():
		if not present.has(id):
			removed.append(str(id))
	var clean: bool = new_ids.is_empty() and changed.is_empty() and removed.is_empty() and unsupported.is_empty() and broken.is_empty()
	var text: String = "# Card import report\n\n"
	text += "Generated by `tools/import_cards.gd` from `data/source/card_list.csv`, `token_list.csv` and `data/scripts/*.txt`.\n\n"
	text += "- Cards: %d, tokens: %d (including the three Design-Guidance-only resource tokens)\n" % [cards, tokens]
	text += "- Status: **%s**\n\n" % ("CLEAN - every card and token is scripted with only supported mechanics" if clean else "NOT CLEAN")
	text += _section("New cards", new_ids, "Cards that are new in the sheet or have no script yet.")
	text += _section("Changed cards (re-script, then run `--stamp`)", changed, "The rules text no longer matches the text the script was written for.")
	text += _section("Removed cards", removed, "Imported before, no longer in the sheet.")
	text += _section("Unsupported mechanics", unsupported, "Ops, values, events or flags the engine does not implement yet.")
	text += _section("Script problems", broken, "Syntax errors in a script.")
	return text


static func _scriptless_needs(entry: CardImporter.Entry) -> bool:
	return entry.problems.has("no script")


static func _section(title: String, lines: Array[String], note: String) -> String:
	var text: String = "## %s (%d)\n\n%s\n\n" % [title, lines.size(), note]
	if lines.is_empty():
		return text + "None.\n\n"
	for line: String in lines:
		text += "- %s\n" % line
	return text + "\n"


static func _problem_count(entries: Array[CardImporter.Entry], previous: Dictionary) -> int:
	var total: int = 0
	for entry: CardImporter.Entry in entries:
		total += entry.problems.size() + entry.unsupported.size()
		if entry.has_script and entry.script_hash != entry.text_hash:
			total += 1
	if not previous.is_empty():
		var present: Dictionary = {}
		for entry: CardImporter.Entry in entries:
			present[entry.id] = true
		for id: Variant in previous.keys():
			if not present.has(id):
				total += 1
	return total


# ---- Resources, manifest, stamping ------------------------------------------------------------------------


func _write_resources(entries: Array[CardImporter.Entry], clean: bool) -> int:
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(CardImporter.CARD_DIR))
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(CardImporter.TOKEN_DIR))
	var keep: Dictionary = {}
	var written: int = 0
	for entry: CardImporter.Entry in entries:
		var dir: String = CardImporter.TOKEN_DIR if entry.is_token else CardImporter.CARD_DIR
		var path: String = "%s%s.tres" % [dir, entry.id]
		keep[path] = true
		entry.data.take_over_path(path)
		if ResourceSaver.save(entry.data, path) == OK:
			written += 1
		else:
			push_error("Could not save %s" % path)
	if clean:
		for dir_path: String in [CardImporter.CARD_DIR, CardImporter.TOKEN_DIR]:
			_remove_stale(dir_path, keep)
	return written


func _remove_stale(dir_path: String, keep: Dictionary) -> void:
	var dir: DirAccess = DirAccess.open(dir_path)
	if dir == null:
		return
	for file_name: String in dir.get_files():
		var path: String = dir_path + file_name
		if (file_name.ends_with(".tres") or file_name.ends_with(".tres.uid")) and not keep.has(path.trim_suffix(".uid")):
			DirAccess.remove_absolute(ProjectSettings.globalize_path(path))
	for sub: String in dir.get_directories():
		_remove_tree(dir_path + sub + "/")
		DirAccess.remove_absolute(ProjectSettings.globalize_path(dir_path + sub))


func _remove_tree(dir_path: String) -> void:
	var dir: DirAccess = DirAccess.open(dir_path)
	if dir == null:
		return
	for file_name: String in dir.get_files():
		DirAccess.remove_absolute(ProjectSettings.globalize_path(dir_path + file_name))
	for sub: String in dir.get_directories():
		_remove_tree(dir_path + sub + "/")
		DirAccess.remove_absolute(ProjectSettings.globalize_path(dir_path + sub))


func _read_manifest() -> Dictionary:
	var result: Dictionary = {}
	var rows: Array[PackedStringArray] = CardImporter.read_csv(MANIFEST_PATH)
	for index: int in range(1, rows.size()):
		if rows[index].size() >= 2:
			result[rows[index][0]] = rows[index][1]
	return result


func _write_manifest(entries: Array[CardImporter.Entry]) -> void:
	var text: String = "Card ID,text hash\n"
	for entry: CardImporter.Entry in entries:
		text += "%s,%s\n" % [entry.id, entry.text_hash]
	_write_text(MANIFEST_PATH, text)


## Rewrites each script header `== ID @hash  # name` with the sheet's current rules-text hash.
func _stamp_scripts(entries: Array[CardImporter.Entry]) -> void:
	var hashes: Dictionary = {}
	for entry: CardImporter.Entry in entries:
		hashes[entry.id] = entry.text_hash
	var dir: DirAccess = DirAccess.open(CardImporter.SCRIPT_DIR)
	var header: RegEx = RegEx.new()
	header.compile("^==\\s+(\\S+)(?:\\s+@[0-9a-f]+)?(.*)$")
	for file_name: String in dir.get_files():
		if not file_name.ends_with(".txt"):
			continue
		var path: String = CardImporter.SCRIPT_DIR + file_name
		var lines: PackedStringArray = FileAccess.get_file_as_string(path).split("\n")
		var out: Array[String] = []
		for line: String in lines:
			var found: RegExMatch = header.search(line)
			if found != null and hashes.has(found.get_string(1)):
				out.append("== %s @%s%s" % [found.get_string(1), hashes[found.get_string(1)], found.get_string(2)])
			else:
				out.append(line)
		_write_text(path, "\n".join(out))


static func _write_text(path: String, text: String) -> void:
	var file: FileAccess = FileAccess.open(path, FileAccess.WRITE)
	if file == null:
		push_error("Could not write %s" % path)
		return
	file.store_string(text)
	file.close()
