extends SceneTree
## New brief, Part E: balance simulation for the 4 corrupted NPCs. Plays a "typical level-3
## player deck" (CorruptedNpcs.reference_player_deck - the 42-card starter plus 3 on-element
## picks, level-3 stats) against each corrupted NPC's real deck/AI/life, for each of the 4
## possible starting elements, and writes/updates the "Corrupted NPCs (Part E)" section of
## docs/balance_report.md (appended after any existing content from tools/run_simulation.gd,
## which owns the rest of that file - this script only ever touches its own section, marked by
## HTML comments).
##   Godot --headless --path . -s res://tools/run_corrupted_npc_simulation.gd -- --games=200

const SECTION_START: String = "<!-- corrupted-npc-report:start -->"
const SECTION_END: String = "<!-- corrupted-npc-report:end -->"
const REPORT_PATH: String = "res://docs/balance_report.md"
const TARGET_LOW: float = 0.55
const TARGET_HIGH: float = 0.70


func _init() -> void:
	var games: int = 200
	for arg: String in OS.get_cmdline_user_args():
		if arg.begins_with("--games="):
			games = int(arg.trim_prefix("--games="))
	var content: ContentSet = ContentLibrary.load_all()
	var level3_row: LevelData = ProgressionTable.row(3)
	var colors: Array[Affinity.Type] = Affinity.colored_types()
	var lines: PackedStringArray = []
	lines.append(SECTION_START)
	lines.append("## Corrupted NPCs (Part E)")
	lines.append("")
	lines.append("Generated by `tools/run_corrupted_npc_simulation.gd`: for each of the 4 corrupted NPCs, a")
	lines.append("\"typical level-3 player deck\" (`CorruptedNpcs.reference_player_deck` - the 42-card starter")
	lines.append("plus 3 on-element picks, level-3 stats: 11 life, 5-card hand) of each of the 4 possible")
	lines.append("starting elements, %d games each (%d per NPC), balanced AI for the player side, the NPC's own" % [games * colors.size() * CorruptedNpcs.IDS.size(), games * colors.size()])
	lines.append("personality for its side. Target band: **55-70% player win rate**.")
	lines.append("")
	lines.append("| Corrupted NPC | vs Beefcake player | vs Gourmand player | vs Root player | vs Necrocrat player | Overall | In target band? |")
	lines.append("|---|---:|---:|---:|---:|---:|:---:|")
	var started: int = Time.get_ticks_msec()
	for npc_id: String in CorruptedNpcs.IDS:
		var npc_ai: AIPersonality = CorruptedNpcs.personality(content, npc_id)
		var row_wins: Array[int] = []
		var total_wins: int = 0
		var total_games: int = 0
		for color: Affinity.Type in colors:
			var player_deck: Deck = CorruptedNpcs.reference_player_deck(content, color)
			var wins: int = 0
			for i: int in range(games):
				var options: GameOptions = GameOptions.new()
				options.rng_seed = 90000 + i
				options.first_player = i % 2
				options.turn_limit = 60
				options.record_events = false
				var game: GameState = GameState.new(options)
				var p0: PlayerSetup = PlayerSetup.create(player_deck, null, [] as Array[ModifierSource], "Player")
				p0.profile.max_life = level3_row.max_life
				p0.profile.opening_hand_size = level3_row.opening_hand_size
				game.add_player(p0)
				game.add_player(CorruptedNpcs.enemy_setup(content, npc_id))
				game.start()
				var ais: Array[AIPlayer] = [AIPlayer.new(AIPersonality.balanced()), AIPlayer.new(npc_ai)]
				var steps: int = 0
				while not game.is_over() and steps < 5000:
					steps += 1
					var who: int = game.awaiting_player()
					var action: GameAction = ais[who].choose_action(game)
					if not game.apply_action(action):
						if not game.apply_action(GameAction.pass_phase(who)):
							break
				if game.winner == 0:
					wins += 1
			row_wins.append(wins)
			total_wins += wins
			total_games += games
		var overall: float = float(total_wins) / float(total_games)
		var in_band: bool = overall >= TARGET_LOW and overall <= TARGET_HIGH
		var cells: PackedStringArray = []
		for w: int in row_wins:
			cells.append("%.1f%%" % (100.0 * float(w) / float(games)))
		lines.append("| %s (%s) | %s | %s | %s | %s | **%.1f%%** | %s |" % [
			CorruptedNpcs.display_name(npc_id), npc_id, cells[0], cells[1], cells[2], cells[3],
			overall * 100.0, "yes" if in_band else "NO",
		])
	lines.append("")
	lines.append("Simulated in %.1fs." % (float(Time.get_ticks_msec() - started) / 1000.0))
	lines.append(SECTION_END)
	_write_section(String("\n").join(lines))
	quit(0)


func _write_section(new_section: String) -> void:
	var path: String = ProjectSettings.globalize_path(REPORT_PATH)
	var existing: String = ""
	if FileAccess.file_exists(REPORT_PATH):
		existing = FileAccess.get_file_as_string(REPORT_PATH)
	var start_idx: int = existing.find(SECTION_START)
	var end_idx: int = existing.find(SECTION_END)
	var result: String
	if start_idx != -1 and end_idx != -1:
		result = existing.substr(0, start_idx) + new_section + existing.substr(end_idx + SECTION_END.length())
	elif existing.is_empty():
		result = "# Balance Report\n\n" + new_section + "\n"
	else:
		result = existing.rstrip("\n") + "\n\n" + new_section + "\n"
	var file: FileAccess = FileAccess.open(path, FileAccess.WRITE)
	file.store_string(result)
	file.close()
	print("wrote ", REPORT_PATH)
