extends SceneTree
## Fourth brief, Part F: balance simulation for the Graveyard's scripted battle - a "level-
## appropriate deck" (a real, solid, legal 45-card on-color deck, level-25 stats: all 5 equipment
## slots reachable) with no gear vs. the same deck/level with a full loadout of the 5 advanced
## equipment pieces (one per slot - "good equipment"). Also isolates each advanced piece alone to
## report which gear matters most. Writes/updates the "The Graveyard (Part F)" section of
## docs/balance_report.md (its own section, marked by HTML comments, alongside the corrupted
## NPCs' own section - each simulation tool only ever touches its own section).
##   Godot --headless --path . -s res://tools/run_graveyard_balance_simulation.gd -- --games=300

const SECTION_START: String = "<!-- graveyard-report:start -->"
const SECTION_END: String = "<!-- graveyard-report:end -->"
const REPORT_PATH: String = "res://docs/balance_report.md"
const NO_GEAR_TARGET: float = 0.10
const GOOD_GEAR_LOW: float = 0.40
const GOOD_GEAR_HIGH: float = 0.60
## One piece per slot - the full "good equipment" loadout.
const ADVANCED_LOADOUT: Array[String] = ["flamethrower", "cheaters_dice", "hover_boots", "thorned_loincloth", "big_brain_beret"]


func _init() -> void:
	var games: int = 300
	var isolation_games: int = 150
	for arg: String in OS.get_cmdline_user_args():
		if arg.begins_with("--games="):
			games = int(arg.trim_prefix("--games="))
		if arg.begins_with("--isolation-games="):
			isolation_games = int(arg.trim_prefix("--isolation-games="))
	var content: ContentSet = ContentLibrary.load_all()
	var level_row: LevelData = ProgressionTable.row(25)
	var colors: Array[Affinity.Type] = Affinity.colored_types()
	var lines: PackedStringArray = []
	lines.append(SECTION_START)
	lines.append("## The Graveyard (Part F)")
	lines.append("")
	lines.append("Generated by `tools/run_graveyard_balance_simulation.gd`: a \"level-appropriate\" player")
	lines.append("(`CorruptedNpcs.reference_player_deck` - a real, solid, legal 45-card on-color deck -")
	lines.append("at level 25 stats: %d HP, %d-card opening hand, all 5 equipment slots reachable) against" % [level_row.max_hp, level_row.opening_hand_size])
	lines.append("The Restless Dead, balanced AI for the player side, `%s` for the boss. %d games per color" % [GraveyardBoss.AI_NAME, games])
	lines.append("with no gear, %d with the full 5-piece advanced loadout (\"good equipment\") - target bands:" % games)
	lines.append("**under %d%% with no gear, %d-%d%% with good equipment**." % [int(NO_GEAR_TARGET * 100.0), int(GOOD_GEAR_LOW * 100.0), int(GOOD_GEAR_HIGH * 100.0)])
	lines.append("")
	lines.append("| Player element | No gear | Full advanced loadout |")
	lines.append("|---|---:|---:|")
	var started: int = Time.get_ticks_msec()
	var no_gear_total_wins: int = 0
	var no_gear_total_games: int = 0
	var good_gear_total_wins: int = 0
	var good_gear_total_games: int = 0
	for color: Affinity.Type in colors:
		var player_deck: Deck = CorruptedNpcs.reference_player_deck(content, color)
		var no_gear_wins: int = _play_matches(player_deck, level_row, [] as Array[String], content, games)
		var good_gear_wins: int = _play_matches(player_deck, level_row, ADVANCED_LOADOUT, content, games)
		no_gear_total_wins += no_gear_wins
		no_gear_total_games += games
		good_gear_total_wins += good_gear_wins
		good_gear_total_games += games
		lines.append("| %s | %.1f%% | %.1f%% |" % [
			Affinity.display_name(color), 100.0 * float(no_gear_wins) / float(games), 100.0 * float(good_gear_wins) / float(games),
		])
	var no_gear_overall: float = float(no_gear_total_wins) / float(no_gear_total_games)
	var good_gear_overall: float = float(good_gear_total_wins) / float(good_gear_total_games)
	lines.append("| **Overall** | **%.1f%%** | **%.1f%%** |" % [no_gear_overall * 100.0, good_gear_overall * 100.0])
	lines.append("")
	var no_gear_ok: bool = no_gear_overall < NO_GEAR_TARGET
	var good_gear_ok: bool = good_gear_overall >= GOOD_GEAR_LOW and good_gear_overall <= GOOD_GEAR_HIGH
	lines.append("No-gear target (under %d%%): %s. Good-equipment target (%d-%d%%): %s." % [
		int(NO_GEAR_TARGET * 100.0), "met" if no_gear_ok else "NOT MET",
		int(GOOD_GEAR_LOW * 100.0), int(GOOD_GEAR_HIGH * 100.0), "met" if good_gear_ok else "NOT MET",
	])
	lines.append("")
	lines.append("### Which gear matters most")
	lines.append("")
	lines.append("Each advanced piece in isolation (one slot filled, the other 4 empty), %d games against a" % isolation_games)
	lines.append("single reference color (%s) - isolates each piece's own contribution rather than the" % Affinity.display_name(colors[0]))
	lines.append("full loadout's combined effect.")
	lines.append("")
	lines.append("| Piece alone | Win rate |")
	lines.append("|---|---:|")
	var reference_deck: Deck = CorruptedNpcs.reference_player_deck(content, colors[0])
	var isolation_results: Array[Dictionary] = []
	for piece_id: String in ADVANCED_LOADOUT:
		var wins: int = _play_matches(reference_deck, level_row, [piece_id] as Array[String], content, isolation_games)
		var rate: float = float(wins) / float(isolation_games)
		var piece: EquipmentData = content.equipment_piece(piece_id)
		isolation_results.append({"name": piece.source_name if piece != null else piece_id, "rate": rate})
	isolation_results.sort_custom(func(a: Dictionary, b: Dictionary) -> bool: return float(a["rate"]) > float(b["rate"]))
	for entry: Dictionary in isolation_results:
		lines.append("| %s | %.1f%% |" % [str(entry["name"]), float(entry["rate"]) * 100.0])
	lines.append("")
	lines.append("Simulated in %.1fs." % (float(Time.get_ticks_msec() - started) / 1000.0))
	lines.append(SECTION_END)
	_write_section(String("\n").join(lines))
	quit(0 if (no_gear_ok and good_gear_ok) else 1)


## Plays `games` games of `player_deck` (level_row stats, `equipment_ids` equipped) vs. the
## Graveyard boss, alternating who goes first, and returns the player's win count.
func _play_matches(player_deck: Deck, level_row: LevelData, equipment_ids: Array[String], content: ContentSet, games: int) -> int:
	var wins: int = 0
	for i: int in range(games):
		var options: GameOptions = GameOptions.new()
		options.rng_seed = 500000 + i
		options.first_player = i % 2
		options.turn_limit = 60
		options.record_events = false
		var game: GameState = GameState.new(options)
		var p0: PlayerSetup = PlayerSetup.create(player_deck, null, [] as Array[ModifierSource], "Player")
		p0.profile.max_hp = level_row.max_hp
		p0.profile.opening_hand_size = level_row.opening_hand_size
		for equipment_id: String in equipment_ids:
			var piece: EquipmentData = content.equipment_piece(equipment_id)
			if piece != null:
				p0.profile.equipment.append(piece)
		p0.modifiers = p0.profile.gear_modifiers()
		game.add_player(p0)
		game.add_player(GraveyardBoss.enemy_setup(content))
		game.start()
		var ais: Array[AIPlayer] = [AIPlayer.new(AIPersonality.balanced()), AIPlayer.new(GraveyardBoss.personality(content))]
		var steps: int = 0
		while not game.is_over() and steps < 5000:
			steps += 1
			var who: int = game.awaiting_player()
			var action: GameAction = ais[who].choose_action(game)
			if not game.apply_action(action):
				if not game.apply_action(GameAction.pass_phase(who)):
					break
		if game.winner == 0:
			wins += 1
	return wins


func _write_section(new_section: String) -> void:
	var path: String = ProjectSettings.globalize_path(REPORT_PATH)
	var existing: String = ""
	if FileAccess.file_exists(REPORT_PATH):
		existing = FileAccess.get_file_as_string(REPORT_PATH)
	var start_idx: int = existing.find(SECTION_START)
	var end_idx: int = existing.find(SECTION_END)
	var result: String
	if start_idx != -1 and end_idx != -1:
		result = existing.substr(0, start_idx) + new_section + existing.substr(end_idx + SECTION_END.length())
	elif existing.is_empty():
		result = "# Balance Report\n\n" + new_section + "\n"
	else:
		result = existing.rstrip("\n") + "\n\n" + new_section + "\n"
	var file: FileAccess = FileAccess.open(path, FileAccess.WRITE)
	file.store_string(result)
	file.close()
	print("wrote ", REPORT_PATH)
